import {
  LayoutDashboard,
  FolderKanban,
  Calendar,
  Users,
  HardHat,
  UserCircle,
  Building2,
  MapPin,
  LogOut,
  ChevronDown,
  Search,
  Filter,
  Download,
  Plus,
  ArrowLeft,
  Mail,
  Phone,
  Star,
  MessageSquare,
  FileText,
  Camera,
  Clock,
  DollarSign,
  Upload,
  Trash2,
  Edit2,
  CheckCircle,
  TrendingUp,
  Shield,
  Award,
  Wrench,
  Cloud,
  CloudRain,
  CloudSnow,
  Sun,
  CloudLightning
} from 'lucide-react';

export const icons = {
  dashboard: LayoutDashboard,
  projects: FolderKanban,
  calendar: Calendar,
  users: Users,
  crew: HardHat,
  user: UserCircle,
  building: Building2,
  location: MapPin,
  logout: LogOut,
  chevronDown: ChevronDown,
  search: Search,
  filter: Filter,
  download: Download,
  plus: Plus,
  back: ArrowLeft,
  mail: Mail,
  phone: Phone,
  star: Star,
  message: MessageSquare,
  document: FileText,
  camera: Camera,
  clock: Clock,
  money: DollarSign,
  upload: Upload,
  delete: Trash2,
  edit: Edit2,
  check: CheckCircle,
  chart: TrendingUp,
  shield: Shield,
  award: Award,
  wrench: Wrench,
  // Weather icons
  cloud: Cloud,
  rain: CloudRain,
  snow: CloudSnow,
  sun: Sun,
  storm: CloudLightning
} as const;